commands:
  - type: browser
    cmd: visit
    url: "http://40.118.57.244/zm/"
    creates_session: "cas_session"

  # Time to prepare the recording
  - type: sleep
    seconds: 30

  # Start the recording here
  - type: sleep
    seconds: 4

  # Type in the username (0:04)
  - type: browser
    cmd: type
    text: "admin"
    selector: "input[name='username']"
    session: "cas_session"

  - type: sleep
    seconds: 3

  # Type in the password (0:07)
  - type: browser
    cmd: type
    text: "thIs_i5_A_tESt_PasSw0Rd"
    selector: "input[name='password']"
    session: "cas_session"

  - type: sleep
    seconds: 8

  # press login button (0:15)
  - type: browser
    cmd: click
    selector: "button[type='submit']"
    session: "cas_session"

  - type: sleep
    seconds: 7

  # click on monitor 1 (0:22)
  - type: browser
    cmd: click
    selector: "#monitor_id-1 > td.colName > a"
    session: "cas_session"

  - type: sleep
    seconds: 16

  # click on console (0:38)
  - type: browser
    cmd: click
    selector: "#getConsoleHTML > a"
    session: "cas_session"

  - type: sleep
    seconds: 9

  # click on groups (0:47)
  - type: browser
    cmd: click
    selector: "#getGroupsHTML > a"
    session: "cas_session"

  - type: sleep
    seconds: 7

  # click on options (0:54)
  - type: browser
    cmd: click
    selector: "#getOptionsHTML > a"
    session: "cas_session"

  - type: sleep
    seconds: 4

  # click on users (0:58)
  - type: browser
    cmd: click
    selector: "#sidebar > ul > li:nth-child(17) > a"
    session: "cas_session"

  - type: sleep
    seconds: 5

  # click add new user (1:03)
  - type: browser
    cmd: click
    selector: "#contentButtons > button:nth-child(1)"
    session: "cas_session"

  - type: sleep
    seconds: 3

  # fill in username for new user (1:06)
  - type: browser
    cmd: type
    text: "testuser"
    selector: "input[name='newUser\\[Username\\]']"
    session: "cas_session"

  - type: sleep
    seconds: 4

  # fill in password for new user (1:10)
  - type: browser
    cmd: type
    text: "anoTH3er_tESt_PasSw0Rd"
    selector: "input[name='newUser\\[Password\\]']"
    session: "cas_session"

  - type: sleep
    seconds: 8

  # fill in confirm password for new user (1:18)
  - type: browser
    cmd: type
    text: "anoTH3er_tESt_PasSw0Rd"
    selector: "input[name='conf_password']"
    session: "cas_session"

  - type: sleep
    seconds: 4

#  # click on language but don't choose (1:22)
#  - type: browser
#    cmd: click
#    selector: "#contentTable > tbody > tr:nth-child(4) > td > select"
#    session: "cas_session"

  - type: sleep
    seconds: 5

  # click on save (1:27)
  - type: browser
    cmd: click
    selector: "#contentButtons > button:nth-child(1)"
    session: "cas_session"

  - type: sleep
    seconds: 3

  # user exists -> repeat steps
  # fill in username for new user (1:30)
  - type: browser
    cmd: type
    text: "testuser10"
    selector: "input[name='newUser\\[Username\\]']"
    session: "cas_session"

  - type: sleep
    seconds: 4

  # fill in password for new user (1:34)
  - type: browser
    cmd: type
    text: "anoTH3er_tESt_PasSw0Rd"
    selector: "input[name='newUser\\[Password\\]']"
    session: "cas_session"

  - type: sleep
    seconds: 3

  # fill in confirm password for new user (1:37)
  - type: browser
    cmd: type
    text: "anoTH3er_tESt_PasSw0Rd"
    selector: "input[name='conf_password']"
    session: "cas_session"

  - type: sleep
    seconds: 4

  # click on save (1:41)
  - type: browser
    cmd: click
    selector: "#contentButtons > button:nth-child(1)"
    session: "cas_session"

  - type: sleep
    seconds: 20

  # user exists -> repeat steps
  # fill in username for new user (2:01)
  - type: browser
    cmd: type
    text: "testuser111"
    selector: "input[name='newUser\\[Username\\]']"
    session: "cas_session"

  - type: sleep
    seconds: 7

  # fill in password for new user (2:08)
  - type: browser
    cmd: type
    text: "anoTH3er_tESt_PasSw0Rd"
    selector: "input[name='newUser\\[Password\\]']"
    session: "cas_session"

  - type: sleep
    seconds: 3

  # fill in confirm password for new user (2:11)
  - type: browser
    cmd: type
    text: "anoTH3er_tESt_PasSw0Rd"
    selector: "input[name='conf_password']"
    session: "cas_session"

  - type: sleep
    seconds: 3

  # click on save (2:15)
  - type: browser
    cmd: click
    selector: "#contentButtons > button:nth-child(1)"
    session: "cas_session"

  - type: sleep
    seconds: 11

  # click on Montage (2:26)
  - type: browser
    cmd: click
    selector: "#getMontageHTML > a"
    session: "cas_session"

  - type: sleep
    seconds: 19

  # click on admin (2:45)
  - type: browser
    cmd: click
    selector: "#logoutButton"
    session: "cas_session"

  - type: sleep
    seconds: 7

  # log out (2:52)
  - type: browser
    cmd: click
    selector: "#logoutForm > button:nth-child(2)"
    session: "cas_session"

  - type: sleep
    seconds: 3
