[project]
name = "playbookgen"
version = "0.1.0"
dependencies = [
    "pathspec==0.12.1",
    "openai==0.27.0",
    "python-dotenv==1.0.1",
    "playwright==1.50.0",
    "PyYAML==6.0.2"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
