[project]
name = "playbookgen"
version = "0.1.0"
dependencies = [
    "pathspec",
    "openai",
    "python-dotenv",
    "playwright",
    "PyYAML",
    "openai-agents",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
