# File: zoneminder_admin.yml
vars:
  ZM_URL: "http://172.17.100.121"  # Replace with your ZoneMinder URL
  USERNAME: "admin"
  PASSWORD: "zm_VERY_S3CURE_PASSW0RD"
  SCREENSHOT_PATH: "zm_snapshot.png"

commands:
  # Step 1: Login to ZoneMinder
  - type: browser
    cmd: visit
    url: $ZM_URL
    creates_session: "zm_session"

  - type: browser
    cmd: type
    selector: "input[name='username']"
    text: $USERNAME
    session: "zm_session"

  - type: browser
    cmd: type
    selector: "input[name='password']"
    text: $PASSWORD
    session: "zm_session"

  - type: browser
    cmd: click
    selector: ".btn"
    session: "zm_session"

  # Step 2: Check System Health
  - type: browser
    cmd: click
    selector: "a.nav-link[href='?view=console']"
    session: "zm_session"

  # Step 3: Explore Critical Configuration Options
  - type: browser
    cmd: click
    selector: "a.nav-link[href='?view=options']"
    session: "zm_session"

  - type: browser
    cmd: click
    selector: "text=Config"
    session: "zm_session"

  - type: browser
    cmd: click
    selector: "text=Network"
    session: "zm_session"

  # Step 4: Check Live Feeds
  - type: browser
    cmd: click
    selector: "#liveButton"
    session: "zm_session"

  # Step 5: Review Logs
  - type: browser
    cmd: click
    selector: "text=Log"
    session: "zm_session"

  - type: browser
    cmd: click
    selector: "#refreshBtn"
    session: "zm_session"

  # Step 6: Capture System State Snapshot
  - type: browser
    cmd: screenshot
    screenshot_path: $SCREENSHOT_PATH
    session: "zm_session"

  # Logout for Security
  - type: browser
    cmd: click
    selector: "#logoutButton"
    session: "zm_session"

  - type: browser
    cmd: click
    selector: "button[name='action'][value='logout']"
    session: "zm_session"
